### ISSUE TITLE
Not returning ResponseEntity

### ISSUE THREAD

**Issue by canujohann** [lechatthecat/java-challenge#1]
https://github.com/lechatthecat/java-challenge/blob/28d18ccfcf6cdbbc5fe009198e07acb1de500984/src/main/java/jp/co/axa/apidemo/controllers/EmployeeController.java#L53

Maybe better/consistent to return an ResponseEntity instance ?

**Comment by lechatthecat** [comment]
Thank you very much for the comment. Fixed the method to return ResponseEntity.

**Comment by lechatthecat** [comment]
Closing this issue. If the problem remains, please re-open this issue.
